# Generated by Django 4.1.3 on 2023-01-29 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyschedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 1, 19, 46, 31067, tzinfo=datetime.timezone.utc)),
        ),
    ]
