# Generated by Django 4.1.4 on 2023-01-21 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyschedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 23, 29, 8, 632959, tzinfo=datetime.timezone.utc)),
        ),
    ]
