# Generated by Django 4.1.4 on 2022-12-25 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyschedule', '0002_cronograma_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='aluno',
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyschedule.aluno', verbose_name='criado por'),
        ),
    ]
