# Generated by Django 4.1.4 on 2023-01-21 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailyschedule', '0004_cronograma_aluno_alter_cronograma_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='usuario',
        ),
        migrations.AddField(
            model_name='aluno',
            name='notificacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
