# Generated by Django 4.1.4 on 2023-01-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyschedule', '0002_alter_aluno_last_login'),
        ('dailyschedule', '0004_cronograma_aluno_alter_cronograma_created_by'),
    ]

    operations = [
    ]
