# Generated by Django 4.1.4 on 2023-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyschedule', '0005_remove_aluno_nome_remove_aluno_senha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='user',
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='senha',
            field=models.CharField(default='123', max_length=30),
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
