# Generated by Django 4.1.4 on 2023-01-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyschedule', '0007_aluno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='qtd',
            field=models.IntegerField(default=0),
        ),
    ]
